task_id: "task3" # e.g., widget_01, bracket_complex_v2
description: "This is a 10mm thick circular plate that has two holes. It's a concentric circle (sort of like a gasket). 

1. The outer diameter of the plate is 100mm and the inner diameter is 50mm. 

2. There are two holes through the plate. One hole is at the 12 o'clock position (at the top of the plate). It's halfway between the inner diameter and outer diameter (so the center hole is 37.5mm from the center of the circular plate. The hole is 5mm diameter. 

3. The second hole is in the 3 o'clock position. It's also half way between the inner and outer diameter of the plate. This hole is 10mm in diameter."
reference_stl: "./reference/task3.stl" # Path relative to project root, ensure the STL file exists here.
requirements:
  bounding_box: [100, 100, 10]
  topology_requirements:
    expected_component_count: 1
manual_operations: 3